"""empty message

Revision ID: 027529ad2e30
Revises: 3e1da2df8933
Create Date: 2021-08-01 19:17:02.279080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '027529ad2e30'
down_revision = '3e1da2df8933'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
